version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /.github/actions/bootstrap
      - /
    schedule:
      interval: cron
      cronjob: '15 5 * * *' # Every day at 5:15 AM
      timezone: Etc/UTC
    cooldown:
      default-days: 7
      include:
        - '*'
    allow:
      - dependency-type: all
    commit-message:
      prefix: build
      include: scope
    groups:
      minor:
        patterns:
          - '*'
        exclude-patterns:
          - 1password/load-secrets-action
          - 1password/load-secrets-action/*
          - actions/create-github-app-token
        update-types:
          - minor
      patch:
        patterns:
          - '*'
        exclude-patterns:
          - 1password/load-secrets-action
          - 1password/load-secrets-action/*
          - actions/create-github-app-token
        update-types:
          - patch
    labels:
      - ':horse: chore'
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directories:
      - /
    schedule:
      interval: cron
      cronjob: '15 5 * * *' # Every day at 5:15 AM
      timezone: Etc/UTC
    cooldown:
      default-days: 7
      include:
        - '*'
    allow:
      - dependency-type: all
    commit-message:
      prefix: build
      include: scope
    groups:
      minor:
        patterns:
          - '*'
        exclude-patterns:
          - '@ariga/atlas'
          - '@tursodatabase/*'
          - drizzle-*
        update-types:
          - minor
      patch:
        patterns:
          - '*'
        exclude-patterns:
          - '@ariga/atlas'
          - '@tursodatabase/*'
          - drizzle-*
        update-types:
          - patch
    ignore:
      - dependency-name: typescript
        versions: '>=7.0.0'
    labels:
      - ':horse: chore'
    open-pull-requests-limit: 10
    versioning-strategy: increase
