compressionLevel: mixed
enableTelemetry: false
nmHoistingLimits: workspaces
nmSelfReferences: false
nodeLinker: node-modules
npmMinimalAgeGate: 10080 # 7 days
packageExtensions:
  '@commitlint/load@*':
    dependencies:
      '@types/node': '*'
      typescript: '*'
  '@storybook/addon-docs@*':
    dependencies:
      '@types/react': '*'
  '@storybook/addon-vitest@*':
    dependencies:
      react: '*'
      react-dom: '*'
  '@storybook/react-vite@*':
    dependencies:
      typescript: '*'
  eslint-plugin-perfectionist@*:
    dependencies:
      typescript: '*'
  eslint-plugin-storybook@*:
    dependencies:
      typescript: '*'
  eslint-plugin-testing-library@*:
    dependencies:
      typescript: '*'
  storybook-i18n@*:
    dependencies:
      react: '*'
      react-dom: '*'
  storybook@*:
    dependencies:
      react: '*'
      react-dom: '*'
supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
